version: "2"

linters:
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  settings:
    funlen:
      lines: 120
      statements: 120
    dupl:
      threshold: 200
    gocognit:
      min-complexity: 32
  exclusions:
    rules:
      - path: (.+)_test.go
        linters:
          - funlen
          - gocritic
          - gocognit

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
